[package]
name = "injector"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_Debug",
] }
