[package]
name = "hookdll"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"] # builds a .dll

[dependencies]
windows = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Direct3D",
] }
detour = "0.7" # for function hooking
imgui = "0.7.0" # core ImGui
imgui-dx11-renderer = "0.7" # ImGui DX11 backend
imgui-winit-support = "0.7" # needed for Win32 binding
