[package]
name = "hookdll"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"] # builds a .dll

[dependencies]
windows = { version = "0.52.0", features = [
    "Win32_Foundation",
    "Win32_System_SystemServices",
] }
